# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  web-deploy:
    name: Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        protocol: ftps
        port: 22
        exclude: |
          .gitignore
          **/.git*
          **/.git*/**
          **/node_modules/**
